### ISSUE TITLE
Client.pm should accept an array, not a single value

### ISSUE THREAD

**Issue by scottchiefbaker** [claesjac/JSON-RPC-Simple#4]
In Client.pm line #60 it gets the params from from AUTOLOAD. That only allows you to send a single value (or a reference) to a method call. Thus if I had a method call like:

```
$obj->echo_data(2,4,6);
```

Only the 2 will get sent. I believe line #60 should be changed to `@params`

**Comment by scottchiefbaker** [comment]
It works as is if you do:

`$obj->echo_data([2,4,6]);`

But that seems a lot less intuitive than using `@params` to capture the params more naturally.

**Comment by claesjac** [comment]
It's that way because it's the only way to differentiate between positional and named arguments so the current way it handles it is correct. If it's is kept as is then the second argument could be a "options" hash with things like ns $client->baz($args, { namespace => "foo.bar" }). But I'm not really fond of that either

**Comment by scottchiefbaker** [comment]
Ah good point... I don't use named parameters so it didn't cross my mind.
